package com.joyotime.xr87.job.util;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.joyotime.xr87.util.ip.IPSeeker;

/**
 * 任务应用会用到的一些缓存对象
 *
 *
 * @author chenglin.zhu@gmail.com
 * @date 2012-8-23
 */

public class BaseInfo {
	// 地区信息
	public static Map<String, List<String>> district;
	// IP地址查询对象
	public static IPSeeker ipSeeker;
	/**
	// 线程的sleep时间
	public static long sleepTime = 100;
	// 用户工程监听的PORT
	public static int serverPort = 1312;
	// 存放每日统计accesslog的数据文件夹
	public static String dataPath = Tools.root + Tools.fileSepa + "data" + Tools.fileSepa;
	*/
	
	public static Map<String, String> config = new HashMap<String, String>();
	
	public BaseInfo() {
		initDistrict();
		BaseInfo.ipSeeker = IPSeeker.getInstance();
	}
	
	/**
	 * 设置配置信息
	 */
	public void setConfig(Map<String, String> config) {
		BaseInfo.config = config;
	}
	
	/**
	 * 初始化地区信息
	 */
	private void initDistrict() {
		BaseInfo.district = new HashMap<String, List<String>>();
		List<String> list = new ArrayList<String>();
		list.add("东城区");
		list.add("西城区");
		list.add("崇文区");
		list.add("宣武区");
		list.add("朝阳区");
		list.add("丰台区");
		list.add("石景山区");
		list.add("海淀区");
		list.add("门头沟区");
		list.add("房山区");
		list.add("通州区");
		list.add("顺义区");
		list.add("昌平区");
		list.add("大兴区");
		list.add("怀柔区");
		list.add("平谷区");
		list.add("密云县");
		list.add("延庆县");
		BaseInfo.district.put("北京", list);
		list = new ArrayList<String>();
		list.add("和平区");
		list.add("河东区");
		list.add("河西区");
		list.add("南开区");
		list.add("河北区");
		list.add("红桥区");
		list.add("塘沽区");
		list.add("汉沽区");
		list.add("大港区");
		list.add("东丽区");
		list.add("西青区");
		list.add("津南区");
		list.add("北辰区");
		list.add("武清区");
		list.add("宝坻区");
		list.add("宁河县");
		list.add("静海县");
		list.add("蓟县");
		BaseInfo.district.put("天津", list);
		list = new ArrayList<String>();
		list.add("石家庄市");
		list.add("唐山市");
		list.add("秦皇岛市");
		list.add("邯郸市");
		list.add("邢台市");
		list.add("保定市");
		list.add("张家口市");
		list.add("承德市");
		list.add("衡水市");
		list.add("廊坊市");
		list.add("沧州市");
		BaseInfo.district.put("河北", list);
		list = new ArrayList<String>();
		list.add("太原市");
		list.add("大同市");
		list.add("阳泉市");
		list.add("长治市");
		list.add("晋城市");
		list.add("朔州市");
		list.add("晋中市");
		list.add("运城市");
		list.add("忻州市");
		list.add("临汾市");
		list.add("吕梁市");
		BaseInfo.district.put("山西", list);
		list = new ArrayList<String>();
		list.add("呼和浩特市");
		list.add("包头市");
		list.add("乌海市");
		list.add("赤峰市");
		list.add("通辽市");
		list.add("鄂尔多斯市");
		list.add("呼伦贝尔市");
		list.add("巴彦淖尔市");
		list.add("乌兰察布市");
		list.add("兴安盟");
		list.add("锡林郭勒盟");
		list.add("阿拉善盟");
		BaseInfo.district.put("内蒙古", list);
		list = new ArrayList<String>();
		list.add("沈阳市");
		list.add("大连市");
		list.add("鞍山市");
		list.add("抚顺市");
		list.add("本溪市");
		list.add("丹东市");
		list.add("锦州市");
		list.add("营口市");
		list.add("阜新市");
		list.add("辽阳市");
		list.add("盘锦市");
		list.add("铁岭市");
		list.add("朝阳市");
		list.add("葫芦岛市");
		BaseInfo.district.put("辽宁", list);
		list = new ArrayList<String>();
		list.add("长春市");
		list.add("吉林市");
		list.add("四平市");
		list.add("辽源市");
		list.add("通化市");
		list.add("白山市");
		list.add("松原市");
		list.add("白城市");
		list.add("延边朝鲜族自治州");
		BaseInfo.district.put("吉林", list);
		list = new ArrayList<String>();
		list.add("哈尔滨市");
		list.add("齐齐哈尔市");
		list.add("鸡西市");
		list.add("鹤岗市");
		list.add("双鸭山市");
		list.add("大庆市");
		list.add("伊春市");
		list.add("佳木斯市");
		list.add("七台河市");
		list.add("牡丹江市");
		list.add("黑河市");
		list.add("绥化市");
		list.add("大兴安岭地区");
		BaseInfo.district.put("黑龙江", list);
		list = new ArrayList<String>();
		list.add("黄浦区");
		list.add("卢湾区");
		list.add("徐汇区");
		list.add("长宁区");
		list.add("静安区");
		list.add("普陀区");
		list.add("闸北区");
		list.add("虹口区");
		list.add("杨浦区");
		list.add("闵行区");
		list.add("宝山区");
		list.add("嘉定区");
		list.add("浦东新区");
		list.add("金山区");
		list.add("松江区");
		list.add("青浦区");
		list.add("南汇区");
		list.add("奉贤区");
		list.add("崇明县");
		BaseInfo.district.put("上海", list);
		list = new ArrayList<String>();
		list.add("南京市");
		list.add("无锡市");
		list.add("徐州市");
		list.add("常州市");
		list.add("苏州市");
		list.add("南通市");
		list.add("连云港市");
		list.add("淮安市");
		list.add("盐城市");
		list.add("扬州市");
		list.add("镇江市");
		list.add("泰州市");
		list.add("宿迁市");
		BaseInfo.district.put("江苏", list);
		list = new ArrayList<String>();
		list.add("杭州市");
		list.add("宁波市");
		list.add("温州市");
		list.add("嘉兴市");
		list.add("湖州市");
		list.add("绍兴市");
		list.add("舟山市");
		list.add("衢州市");
		list.add("金华市");
		list.add("台州市");
		list.add("丽水市");
		BaseInfo.district.put("浙江", list);
		list = new ArrayList<String>();
		list.add("合肥市");
		list.add("芜湖市");
		list.add("蚌埠市");
		list.add("淮南市");
		list.add("马鞍山市");
		list.add("淮北市");
		list.add("铜陵市");
		list.add("安庆市");
		list.add("黄山市");
		list.add("滁州市");
		list.add("阜阳市");
		list.add("宿州市");
		list.add("巢湖市");
		list.add("六安市");
		list.add("亳州市");
		list.add("池州市");
		list.add("宣城市");
		BaseInfo.district.put("安徽", list);
		list = new ArrayList<String>();
		list.add("福州市");
		list.add("厦门市");
		list.add("莆田市");
		list.add("三明市");
		list.add("泉州市");
		list.add("漳州市");
		list.add("南平市");
		list.add("龙岩市");
		list.add("宁德市");
		BaseInfo.district.put("福建", list);
		list = new ArrayList<String>();
		list.add("南昌市");
		list.add("景德镇市");
		list.add("萍乡市");
		list.add("九江市");
		list.add("新余市");
		list.add("鹰潭市");
		list.add("赣州市");
		list.add("吉安市");
		list.add("宜春市");
		list.add("抚州市");
		list.add("上饶市");
		BaseInfo.district.put("江西", list);
		list = new ArrayList<String>();
		list.add("济南市");
		list.add("青岛市");
		list.add("淄博市");
		list.add("枣庄市");
		list.add("东营市");
		list.add("烟台市");
		list.add("潍坊市");
		list.add("济宁市");
		list.add("泰安市");
		list.add("威海市");
		list.add("日照市");
		list.add("莱芜市");
		list.add("临沂市");
		list.add("德州市");
		list.add("聊城市");
		list.add("滨州市");
		list.add("菏泽市");
		BaseInfo.district.put("山东", list);
		list = new ArrayList<String>();
		list.add("郑州市");
		list.add("开封市");
		list.add("洛阳市");
		list.add("平顶山市");
		list.add("安阳市");
		list.add("鹤壁市");
		list.add("新乡市");
		list.add("焦作市");
		list.add("濮阳市");
		list.add("许昌市");
		list.add("漯河市");
		list.add("三门峡市");
		list.add("南阳市");
		list.add("商丘市");
		list.add("信阳市");
		list.add("周口市");
		list.add("驻马店市");
		list.add("济源市");
		BaseInfo.district.put("河南", list);
		list = new ArrayList<String>();
		list.add("武汉市");
		list.add("黄石市");
		list.add("十堰市");
		list.add("宜昌市");
		list.add("襄樊市");
		list.add("鄂州市");
		list.add("荆门市");
		list.add("孝感市");
		list.add("荆州市");
		list.add("黄冈市");
		list.add("咸宁市");
		list.add("随州市");
		list.add("恩施土家族苗族自治州");
		list.add("仙桃市");
		list.add("潜江市");
		list.add("天门市");
		list.add("神农架林区");
		BaseInfo.district.put("湖北", list);
		list = new ArrayList<String>();
		list.add("长沙市");
		list.add("株洲市");
		list.add("湘潭市");
		list.add("衡阳市");
		list.add("邵阳市");
		list.add("岳阳市");
		list.add("常德市");
		list.add("张家界市");
		list.add("益阳市");
		list.add("郴州市");
		list.add("永州市");
		list.add("怀化市");
		list.add("娄底市");
		list.add("湘西土家族苗族自治州");
		BaseInfo.district.put("湖南", list);
		list = new ArrayList<String>();
		list.add("广州市");
		list.add("韶关市");
		list.add("深圳市");
		list.add("珠海市");
		list.add("汕头市");
		list.add("佛山市");
		list.add("江门市");
		list.add("湛江市");
		list.add("茂名市");
		list.add("肇庆市");
		list.add("惠州市");
		list.add("梅州市");
		list.add("汕尾市");
		list.add("河源市");
		list.add("阳江市");
		list.add("清远市");
		list.add("东莞市");
		list.add("中山市");
		list.add("潮州市");
		list.add("揭阳市");
		list.add("云浮市");
		BaseInfo.district.put("广东", list);
		list = new ArrayList<String>();
		list.add("南宁市");
		list.add("柳州市");
		list.add("桂林市");
		list.add("梧州市");
		list.add("北海市");
		list.add("防城港市");
		list.add("钦州市");
		list.add("贵港市");
		list.add("玉林市");
		list.add("百色市");
		list.add("贺州市");
		list.add("河池市");
		list.add("来宾市");
		list.add("崇左市");
		BaseInfo.district.put("广西", list);
		list = new ArrayList<String>();
		list.add("海口市");
		list.add("三亚市");
		list.add("五指山市");
		list.add("琼海市");
		list.add("儋州市");
		list.add("文昌市");
		list.add("万宁市");
		list.add("东方市");
		list.add("定安县");
		list.add("屯昌县");
		list.add("澄迈县");
		list.add("临高县");
		list.add("白沙黎族自治县");
		list.add("昌江黎族自治县");
		list.add("乐东黎族自治县");
		list.add("陵水黎族自治县");
		list.add("保亭黎族苗族自治县");
		list.add("琼中黎族苗族自治县");
		list.add("西沙群岛");
		list.add("南沙群岛");
		list.add("中沙群岛的岛礁及其海域");
		BaseInfo.district.put("海南", list);
		list = new ArrayList<String>();
		list.add("万州区");
		list.add("涪陵区");
		list.add("渝中区");
		list.add("大渡口区");
		list.add("江北区");
		list.add("沙坪坝区");
		list.add("九龙坡区");
		list.add("南岸区");
		list.add("北碚区");
		list.add("双桥区");
		list.add("万盛区");
		list.add("渝北区");
		list.add("巴南区");
		list.add("黔江区");
		list.add("长寿区");
		list.add("綦江县");
		list.add("潼南县");
		list.add("铜梁县");
		list.add("大足县");
		list.add("荣昌县");
		list.add("璧山县");
		list.add("梁平县");
		list.add("城口县");
		list.add("丰都县");
		list.add("垫江县");
		list.add("武隆县");
		list.add("忠县");
		list.add("开县");
		list.add("云阳县");
		list.add("奉节县");
		list.add("巫山县");
		list.add("巫溪县");
		list.add("石柱土家族自治县");
		list.add("秀山土家族苗族自治县");
		list.add("酉阳土家族苗族自治县");
		list.add("彭水苗族土家族自治县");
		list.add("江津市");
		list.add("合川市");
		list.add("永川市");
		list.add("南川市");
		BaseInfo.district.put("重庆", list);
		list = new ArrayList<String>();
		list.add("成都市");
		list.add("自贡市");
		list.add("攀枝花市");
		list.add("泸州市");
		list.add("德阳市");
		list.add("绵阳市");
		list.add("广元市");
		list.add("遂宁市");
		list.add("内江市");
		list.add("乐山市");
		list.add("南充市");
		list.add("眉山市");
		list.add("宜宾市");
		list.add("广安市");
		list.add("达州市");
		list.add("雅安市");
		list.add("巴中市");
		list.add("资阳市");
		list.add("阿坝州");
		list.add("甘孜州");
		list.add("凉山州");
		BaseInfo.district.put("四川", list);
		list = new ArrayList<String>();
		list.add("贵阳市");
		list.add("六盘水市");
		list.add("遵义市");
		list.add("安顺市");
		list.add("铜仁地区");
		list.add("黔西南布依族苗族自治州");
		list.add("毕节地区");
		list.add("黔东南苗族侗族自治州");
		list.add("黔南布依族苗族自治州");
		BaseInfo.district.put("贵州", list);
		list = new ArrayList<String>();
		list.add("昆明市");
		list.add("曲靖市");
		list.add("玉溪市");
		list.add("保山市");
		list.add("昭通市");
		list.add("丽江市");
		list.add("思茅市");
		list.add("临沧市");
		list.add("楚雄彝族自治州");
		list.add("红河哈尼族彝族自治州");
		list.add("文山壮族苗族自治州");
		list.add("西双版纳傣族自治州");
		list.add("大理白族自治州");
		list.add("德宏傣族景颇族自治州");
		list.add("怒江傈僳族自治州");
		list.add("迪庆藏族自治州");
		BaseInfo.district.put("云南", list);
		list = new ArrayList<String>();
		list.add("拉萨市");
		list.add("昌都地区");
		list.add("山南地区");
		list.add("日喀则地区");
		list.add("那曲地区");
		list.add("阿里地区");
		list.add("林芝地区");
		BaseInfo.district.put("西藏", list);
		list = new ArrayList<String>();
		list.add("西安市");
		list.add("铜川市");
		list.add("宝鸡市");
		list.add("咸阳市");
		list.add("渭南市");
		list.add("延安市");
		list.add("汉中市");
		list.add("榆林市");
		list.add("安康市");
		list.add("商洛市");
		BaseInfo.district.put("陕西", list);
		list = new ArrayList<String>();
		list.add("兰州市");
		list.add("嘉峪关市");
		list.add("金昌市");
		list.add("白银市");
		list.add("天水市");
		list.add("武威市");
		list.add("张掖市");
		list.add("平凉市");
		list.add("酒泉市");
		list.add("庆阳市");
		list.add("定西市");
		list.add("陇南市");
		list.add("临夏回族自治州");
		list.add("甘南藏族自治州");
		BaseInfo.district.put("甘肃", list);
		list = new ArrayList<String>();
		list.add("西宁市");
		list.add("海东地区");
		list.add("海北藏族自治州");
		list.add("黄南藏族自治州");
		list.add("海南藏族自治州");
		list.add("果洛藏族自治州");
		list.add("玉树藏族自治州");
		list.add("海西蒙古族藏族自治州");
		BaseInfo.district.put("青海", list);
		list = new ArrayList<String>();
		list.add("银川市");
		list.add("石嘴山市");
		list.add("吴忠市");
		list.add("固原市");
		list.add("中卫市");
		BaseInfo.district.put("宁夏", list);
		list = new ArrayList<String>();
		list.add("乌鲁木齐市");
		list.add("克拉玛依市");
		list.add("吐鲁番地区");
		list.add("哈密地区");
		list.add("昌吉回族自治州");
		list.add("博尔塔拉蒙古自治州");
		list.add("巴音郭楞蒙古自治州");
		list.add("阿克苏地区");
		list.add("克孜勒苏柯尔克孜自治州");
		list.add("喀什地区");
		list.add("和田地区");
		list.add("伊犁哈萨克自治州");
		list.add("塔城地区");
		list.add("阿勒泰地区");
		list.add("石河子市");
		list.add("阿拉尔市");
		list.add("图木舒克市");
		list.add("五家渠市");
		BaseInfo.district.put("新疆", list);
		list = new ArrayList<String>();
		list.add("台北市");
		list.add("高雄市");
		list.add("基隆市");
		list.add("台中市");
		list.add("台南市");
		list.add("新竹市");
		list.add("嘉义市");
		list.add("台北县");
		list.add("宜兰县");
		list.add("桃园县");
		list.add("新竹县");
		list.add("苗栗县");
		list.add("台中县");
		list.add("彰化县");
		list.add("南投县");
		list.add("云林县");
		list.add("嘉义县");
		list.add("台南县");
		list.add("高雄县");
		list.add("屏东县");
		list.add("澎湖县");
		list.add("台东县");
		list.add("花莲县");
		BaseInfo.district.put("台湾", list);
		list = new ArrayList<String>();
		list.add("中西区");
		list.add("东区");
		list.add("九龙城区");
		list.add("观塘区");
		list.add("南区");
		list.add("深水埗区");
		list.add("黄大仙区");
		list.add("湾仔区");
		list.add("油尖旺区");
		list.add("离岛区");
		list.add("葵青区");
		list.add("北区");
		list.add("西贡区");
		list.add("沙田区");
		list.add("屯门区");
		list.add("大埔区");
		list.add("荃湾区");
		list.add("元朗区");
		BaseInfo.district.put("香港", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("澳门", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("美国", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("加拿大", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("澳大利亚", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("新西兰", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("英国", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("法国", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("德国", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("捷克", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("荷兰", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("瑞士", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("希腊", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("挪威", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("瑞典", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("丹麦", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("芬兰", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("爱尔兰", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("奥地利", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("意大利", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("乌克兰", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("俄罗斯", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("西班牙", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("韩国", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("新加坡", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("马来西亚", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("印度", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("泰国", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("日本", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("巴西", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("阿根廷", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("南非", list);
		list = new ArrayList<String>();
		BaseInfo.district.put("埃及", list);
	}
}
